DROP DATABASE IF EXISTS loja_util;

CREATE DATABASE IF NOT EXISTS loja_util;

USE loja_util;

CREATE TABLE IF NOT EXISTS produto (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ativo BOOLEAN NOT NULL,
	sku VARCHAR(50) NOT NULL UNIQUE,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(100),
	valor_unitario DECIMAL(10,2) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS cliente (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ativo BOOLEAN NOT NULL,
	nome VARCHAR(100) NOT NULL,
	cpf_cnpj VARCHAR(14) NOT NULL UNIQUE
);

INSERT INTO cliente (ativo, nome, cpf_cnpj)
VALUES (TRUE, "Bruno Cunha", "12345678910");

SELECT * FROM cliente;

CREATE TABLE IF NOT EXISTS venda (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	data_venda DATETIME NOT NULL,
	status_venda VARCHAR(1) NOT NULL,
	quantidade DECIMAL(10,1) UNSIGNED NOT NULL,
	valor_total DECIMAL(10,2) UNSIGNED NOT NULL,
	cliente_id INT NOT NULL,
	CONSTRAINT fk_venda_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

CREATE TABLE IF NOT EXISTS venda_item (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	quantidade DECIMAL(10,1) UNSIGNED NOT NULL,
	valor_unitario DECIMAL(10,2) UNSIGNED NOT NULL,
	valor_total DECIMAL(10,2) UNSIGNED NOT NULL,
	venda_id INT NOT NULL,
	produto_id INT NOT NULL,
	CONSTRAINT fk_venda_item_venda FOREIGN KEY (venda_id) REFERENCES venda(id),
	CONSTRAINT fk_venda_item_produto FOREIGN KEY (produto_id) REFERENCES produto(id)
);

##DROP TABLE IF EXISTS venda;

SELECT * FROM produto;