INSERT INTO selecoes(sigla, data_cadastro, grupo, nome)
VALUES
('QAT', NOW(), 'A', 'Qatar'),
('ECU', NOW(), 'A', 'Equador'),
('SEN', NOW(), 'A', 'Senegal'),
('NED', NOW(), 'A', 'Holanda'),
('ENG', NOW(), 'B', 'Inglaterra'),
('IRN', NOW(), 'B', 'Irã'),
('USA', NOW(), 'B', 'Estados Unidos'),
('WAL', NOW(), 'B', 'País de Gales'),
('ARG', NOW(), 'C', 'Argentina'),
('KSA', NOW(), 'C', 'Arábia Saudita'),
('MEX', NOW(), 'C', 'México'),
('POL', NOW(), 'C', 'Polônia'),
('FRA', NOW(), 'D', 'França'),
('DEN', NOW(), 'D', 'Dinamarca'),
('TUN', NOW(), 'D', 'Tunísia'),
('AUS', NOW(), 'D', 'Austrália'),
('ESP', NOW(), 'E', 'Espanha'),
('GER', NOW(), 'E', 'Alemanha'),
('JPN', NOW(), 'E', 'Japão'),
('CRC', NOW(), 'E', 'Costa Rica'),
('BEL', NOW(), 'F', 'Bélgica'),
('CAN', NOW(), 'F', 'Canadá'),
('MAR', NOW(), 'F', 'Marrocos'),
('CRO', NOW(), 'F', 'Croácia'),
('BRA', NOW(), 'G', 'Brasil'),
('SRB', NOW(), 'G', 'Sérvia'),
('SUI', NOW(), 'G', 'Suíça'),
('CMR', NOW(), 'G', 'Camarões'),
('POR', NOW(), 'H', 'Portugal'),
('GHA', NOW(), 'H', 'Gana'),
('URU', NOW(), 'H', 'Uruguai'),
('KOR', NOW(), 'H', 'Coréia do Sul');

INSERT INTO jogadores(posicao, nome, sigla)
VALUES
('Defender', 'Juan Foyth', 'ARG'),
('Defender', 'Nicolás Tagliafico', 'ARG'),
('Defender', 'Gonzalo Montiel', 'ARG'),
('Defender', 'Germán Pezzella', 'ARG'),
('Defender', 'Cristian Romero', 'ARG'),
('Defender', 'Nicolás Otamendi', 'ARG'),
('Defender', 'Lisandro Martínez', 'ARG'),
('Defender', 'Nahuel Molina', 'ARG'),
('Forward', 'Julián Álvarez', 'ARG'),
('Forward', 'Lionel Messi', 'ARG'),
('Forward', 'Ángel Di María', 'ARG'),
('Forward', 'Ángel Correa', 'ARG'),
('Forward', 'Paulo Dybala', 'ARG'),
('Forward', 'Lautaro Martínez', 'ARG'),
('Goalkeeper', 'Franco Armani', 'ARG'),
('Goalkeeper', 'Gerónimo Rulli', 'ARG'),
('Goalkeeper', 'Emiliano Martínez', 'ARG'),
('Midfielder', 'Leandro Paredes', 'ARG'),
('Midfielder', 'Rodrigo De Paul', 'ARG'),
('Midfielder', 'Marcos Acuña', 'ARG'),
('Midfielder', 'Exequiel Palacios', 'ARG'),
('Midfielder', 'Thiago Almada', 'ARG'),
('Midfielder', 'Papu Gómez', 'ARG'),
('Midfielder', 'Guido Rodríguez', 'ARG'),
('Midfielder', 'Alexis Mac Allister', 'ARG'),
('Midfielder', 'Enzo Fernández', 'ARG'),

('Defender', 'Miloš Degenek', 'AUS'),
('Defender', 'Nathaniel Atkinson', 'AUS'),
('Defender', 'Kye Rowles', 'AUS'),
('Defender', 'Fran Karačić', 'AUS'),
('Defender', 'Bailey Wright', 'AUS'),
('Defender', 'Aziz Behich', 'AUS'),
('Defender', 'Harry Souttar', 'AUS'),
('Defender', 'Thomas Deng', 'AUS'),
('Defender', 'Joel King', 'AUS'),
('Forward', 'Marco Tilio', 'AUS'),
('Forward', 'Mathew Leckie', 'AUS'),
('Forward', 'Jamie Maclaren', 'AUS'),
('Forward', 'Awer Mabil', 'AUS'),
('Forward', 'Mitchell Duke', 'AUS'),
('Forward', 'Garang Kuol', 'AUS'),
('Forward', 'Craig Goodwin', 'AUS'),
('Forward', 'Jason Cummings', 'AUS'),
('Goalkeeper', 'Mathew Ryan', 'AUS'),
('Goalkeeper', 'Andrew Redmayne', 'AUS'),
('Goalkeeper', 'Danny Vukovic', 'AUS'),
('Midfielder', 'Ajdin Hrustic', 'AUS'),
('Midfielder', 'Aaron Mooy', 'AUS'),
('Midfielder', 'Riley McGree', 'AUS'),
('Midfielder', 'Cameron Devlin', 'AUS'),
('Midfielder', 'Jackson Irvine', 'AUS'),
('Midfielder', 'Keanu Baccus', 'AUS'),

('Defender', 'Toby Alderweireld', 'BEL'),
('Defender', 'Arthur Theate', 'BEL'),
('Defender', 'Wout Faes', 'BEL'),
('Defender', 'Jan Vertonghen', 'BEL'),
('Defender', 'Leander Dendoncker', 'BEL'),
('Defender', 'Zeno Debast', 'BEL'),
('Forward', 'Romelu Lukaku', 'BEL'),
('Forward', 'Eden Hazard', 'BEL'),
('Forward', 'Yannick Carrasco', 'BEL'),
('Forward', 'Dries Mertens', 'BEL'),
('Forward', 'Leandro Trossard', 'BEL'),
('Forward', 'Charles De Ketelaere', 'BEL'),
('Forward', 'Michy Batshuayi', 'BEL'),
('Forward', 'Loïs Openda', 'BEL'),
('Forward', 'Jérémy Doku', 'BEL'),
('Goalkeeper', 'Thibaut Courtois', 'BEL'),
('Goalkeeper', 'Simon Mignolet', 'BEL'),
('Goalkeeper', 'Koen Casteels', 'BEL'),
('Midfielder', 'Axel Witsel', 'BEL'),
('Midfielder', 'Kevin De Bruyne', 'BEL'),
('Midfielder', 'Youri Tielemans', 'BEL'),
('Midfielder', 'Thomas Meunier', 'BEL'),
('Midfielder', 'Thorgan Hazard', 'BEL'),
('Midfielder', 'Amadou Onana', 'BEL'),
('Midfielder', 'Hans Vanaken', 'BEL'),
('Midfielder', 'Timothy Castagne', 'BEL'),

('Defender', 'Danilo', 'BRA'),
('Defender', 'Thiago Silva', 'BRA'),
('Defender', 'Marquinhos', 'BRA'),
('Defender', 'Alex Sandro', 'BRA'),
('Defender', 'Dani Alves', 'BRA'),
('Defender', 'Éder Militão', 'BRA'),
('Defender', 'Alex Telles', 'BRA'),
('Defender', 'Bremer', 'BRA'),
('Forward', 'Richarlison', 'BRA'),
('Forward', 'Neymar', 'BRA'),
('Forward', 'Raphinha', 'BRA'),
('Forward', 'Gabriel Jesus', 'BRA'),
('Forward', 'Antony', 'BRA'),
('Forward', 'Vinícius Júnior', 'BRA'),
('Forward', 'Rodrygo', 'BRA'),
('Forward', 'Pedro', 'BRA'),
('Forward', 'Gabriel Martinelli', 'BRA'),
('Goalkeeper', 'Alisson', 'BRA'),
('Goalkeeper', 'Weverton', 'BRA'),
('Goalkeeper', 'Ederson', 'BRA'),
('Midfielder', 'Casemiro', 'BRA'),
('Midfielder', 'Lucas Paquetá', 'BRA'),
('Midfielder', 'Fred', 'BRA'),
('Midfielder', 'Fabinho', 'BRA'),
('Midfielder', 'Bruno Guimarães', 'BRA'),
('Midfielder', 'Éverton Ribeiro', 'BRA'),

('Defender', 'Jerome Ngom Mbekeli', 'CMR'),
('Defender', 'Nicolas Nkoulou', 'CMR'),
('Defender', 'Christopher Wooh', 'CMR'),
('Defender', 'Olivier Mbaizo', 'CMR'),
('Defender', 'Collins Fai', 'CMR'),
('Defender', 'Jean-Charles Castelletto', 'CMR'),
('Defender', 'Enzo Ebosse', 'CMR'),
('Defender', 'Nouhou Tolo', 'CMR'),
('Forward', 'Moumi Ngamaleu', 'CMR'),
('Forward', 'Jean-Pierre Nsame', 'CMR'),
('Forward', 'Vincent Aboubakar', 'CMR'),
('Forward', 'Christian Bassogog', 'CMR'),
('Forward', 'Karl Toko Ekambi', 'CMR'),
('Forward', 'Eric Maxim Choupo-Moting', 'CMR'),
('Forward', 'Bryan Mbeumo', 'CMR'),
('Goalkeeper', 'Simon Ngapandouetnbu', 'CMR'),
('Goalkeeper', 'Devis Epassy', 'CMR'),
('Goalkeeper', 'André Onana', 'CMR'),
('Midfielder', 'Gaël Ondoua', 'CMR'),
('Midfielder', 'Georges-Kévin Nkoudou', 'CMR'),
('Midfielder', 'André-Frank Zambo Anguissa', 'CMR'),
('Midfielder', 'Samuel Gouet', 'CMR'),
('Midfielder', 'Pierre Kunde', 'CMR'),
('Midfielder', 'Martin Hongla', 'CMR'),
('Midfielder', 'Olivier Ntcham', 'CMR'),
('Midfielder', 'Souaibou Marou', 'CMR'),

('Defender', 'Alistair Johnston', 'CAN'),
('Defender', 'Sam Adekugbe', 'CAN'),
('Defender', 'Kamal Miller', 'CAN'),
('Defender', 'Steven Vitória', 'CAN'),
('Defender', 'Richie Laryea', 'CAN'),
('Defender', 'Derek Cornelius', 'CAN'),
('Defender', 'Joel Waterman', 'CAN'),
('Forward', 'Lucas Cavallini', 'CAN'),
('Forward', 'Tajon Buchanan', 'CAN'),
('Forward', 'Iké Ugbo', 'CAN'),
('Forward', 'Cyle Larin', 'CAN'),
('Forward', 'Alphonso Davies', 'CAN'),
('Forward', 'Jonathan David', 'CAN'),
('Goalkeeper', 'Dayne St. Clair', 'CAN'),
('Goalkeeper', 'James Pantemis', 'CAN'),
('Goalkeeper', 'Milan Borjan', 'CAN'),
('Midfielder', 'Samuel Piette', 'CAN'),
('Midfielder', 'Stephen Eustáquio', 'CAN'),
('Midfielder', 'Liam Fraser', 'CAN'),
('Midfielder', 'Junior Hoilett', 'CAN'),
('Midfielder', 'Atiba Hutchinson', 'CAN'),
('Midfielder', 'Mark-Anthony Kaye', 'CAN'),
('Midfielder', 'Ismaël Koné', 'CAN'),
('Midfielder', 'Jonathan Osorio', 'CAN'),
('Midfielder', 'Liam Millar', 'CAN'),
('Midfielder', 'David Wotherspoon', 'CAN'),

('Defender', 'Juan Pablo Vargas', 'CRC'),
('Defender', 'Keysher Fuller', 'CRC'),
('Defender', 'Óscar Duarte', 'CRC'),
('Defender', 'Bryan Oviedo', 'CRC'),
('Defender', 'Francisco Calvo', 'CRC'),
('Defender', 'Carlos Martínez', 'CRC'),
('Defender', 'Kendall Waston', 'CRC'),
('Defender', 'Rónald Matarrita', 'CRC'),
('Forward', 'Anthony Contreras', 'CRC'),
('Forward', 'Johan Venegas', 'CRC'),
('Forward', 'Joel Campbell', 'CRC'),
('Goalkeeper', 'Keylor Navas', 'CRC'),
('Goalkeeper', 'Esteban Alvarado', 'CRC'),
('Goalkeeper', 'Patrick Sequeira', 'CRC'),
('Midfielder', 'Daniel Chacón', 'CRC'),
('Midfielder', 'Celso Borges', 'CRC'),
('Midfielder', 'Jewison Bennette', 'CRC'),
('Midfielder', 'Bryan Ruiz', 'CRC'),
('Midfielder', 'Gerson Torres', 'CRC'),
('Midfielder', 'Youstin Salas', 'CRC'),
('Midfielder', 'Yeltsin Tejeda', 'CRC'),
('Midfielder', 'Brandon Aguilera', 'CRC'),
('Midfielder', 'Douglas López', 'CRC'),
('Midfielder', 'Roan Wilson', 'CRC'),
('Midfielder', 'Anthony Hernández', 'CRC'),
('Midfielder', 'Álvaro Zamora', 'CRC'),

('Defender', 'Josip Stanišić', 'CRO'),
('Defender', 'Borna Barišić', 'CRO'),
('Defender', 'Martin Erlić', 'CRO'),
('Defender', 'Dejan Lovren', 'CRO'),
('Defender', 'Borna Sosa', 'CRO'),
('Defender', 'Joško Gvardiol', 'CRO'),
('Defender', 'Domagoj Vida', 'CRO'),
('Defender', 'Josip Juranović', 'CRO'),
('Defender', 'Josip Šutalo', 'CRO'),
('Forward', 'Ivan Perišić', 'CRO'),
('Forward', 'Andrej Kramarić', 'CRO'),
('Forward', 'Marko Livaja', 'CRO'),
('Forward', 'Bruno Petković', 'CRO'),
('Forward', 'Ante Budimir', 'CRO'),
('Forward', 'Mislav Oršić', 'CRO'),
('Goalkeeper', 'Dominik Livaković', 'CRO'),
('Goalkeeper', 'Ivo Grbić', 'CRO'),
('Goalkeeper', 'Ivica Ivušić', 'CRO'),
('Midfielder', 'Lovro Majer', 'CRO'),
('Midfielder', 'Mateo Kovačić', 'CRO'),
('Midfielder', 'Luka Modrić', 'CRO'),
('Midfielder', 'Marcelo Brozović', 'CRO'),
('Midfielder', 'Nikola Vlašić', 'CRO'),
('Midfielder', 'Mario Pašalić', 'CRO'),
('Midfielder', 'Luka Sučić', 'CRO'),
('Midfielder', 'Kristijan Jakić', 'CRO'),

('Defender', 'Joachim Andersen', 'DEN'),
('Defender', 'Victor Nelsson', 'DEN'),
('Defender', 'Simon Kjær', 'DEN'),
('Defender', 'Joakim Mæhle', 'DEN'),
('Defender', 'Andreas Christensen', 'DEN'),
('Defender', 'Rasmus Kristensen', 'DEN'),
('Defender', 'Jens Stryger Larsen', 'DEN'),
('Defender', 'Daniel Wass', 'DEN'),
('Defender', 'Alexander Bah', 'DEN'),
('Forward', 'Martin Braithwaite', 'DEN'),
('Forward', 'Kasper Dolberg', 'DEN'),
('Forward', 'Jonas Wind', 'DEN'),
('Forward', 'Yussuf Poulsen', 'DEN'),
('Forward', 'Andreas Cornelius', 'DEN'),
('Goalkeeper', 'Kasper Schmeichel', 'DEN'),
('Goalkeeper', 'Oliver Christensen', 'DEN'),
('Goalkeeper', 'Frederik Rønnow', 'DEN'),
('Midfielder', 'Mathias Jensen', 'DEN'),
('Midfielder', 'Thomas Delaney', 'DEN'),
('Midfielder', 'Christian Eriksen', 'DEN'),
('Midfielder', 'Andreas Skov Olsen', 'DEN'),
('Midfielder', 'Mikkel Damsgaard', 'DEN'),
('Midfielder', 'Christian Nørgaard', 'DEN'),
('Midfielder', 'Pierre-Emile Højbjerg', 'DEN'),
('Midfielder', 'Robert Skov', 'DEN'),
('Midfielder', 'Jesper Lindstrøm', 'DEN'),

('Defender', 'Félix Torres', 'ECU'),
('Defender', 'Piero Hincapié', 'ECU'),
('Defender', 'Robert Arboleda', 'ECU'),
('Defender', 'William Pacho', 'ECU'),
('Defender', 'Pervis Estupiñán', 'ECU'),
('Defender', 'Xavier Arreaga', 'ECU'),
('Defender', 'Ángelo Preciado', 'ECU'),
('Defender', 'Diego Palacios', 'ECU'),
('Defender', 'Jackson Porozo', 'ECU'),
('Forward', 'Michael Estrada', 'ECU'),
('Forward', 'Enner Valencia', 'ECU'),
('Forward', 'Djorkaeff Reasco', 'ECU'),
('Forward', 'Kevin Rodríguez', 'ECU'),
('Goalkeeper', 'Hernán Galíndez', 'ECU'),
('Goalkeeper', 'Moisés Ramírez', 'ECU'),
('Goalkeeper', 'Alexander Domínguez', 'ECU'),
('Midfielder', 'José Cifuentes', 'ECU'),
('Midfielder', 'Carlos Gruezo', 'ECU'),
('Midfielder', 'Ayrton Preciado', 'ECU'),
('Midfielder', 'Romario Ibarra', 'ECU'),
('Midfielder', 'Ángel Mena', 'ECU'),
('Midfielder', 'Jeremy Sarmiento', 'ECU'),
('Midfielder', 'Gonzalo Plata', 'ECU'),
('Midfielder', 'Sebas Méndez', 'ECU'),
('Midfielder', 'Alan Franco', 'ECU'),
('Midfielder', 'Moisés Caicedo', 'ECU'),

('Defender', 'Kyle Walker', 'ENG'),
('Defender', 'Luke Shaw', 'ENG'),
('Defender', 'John Stones', 'ENG'),
('Defender', 'Harry Maguire', 'ENG'),
('Defender', 'Kieran Trippier', 'ENG'),
('Defender', 'Eric Dier', 'ENG'),
('Defender', 'Conor Coady', 'ENG'),
('Defender', 'Trent Alexander-Arnold', 'ENG'),
('Defender', 'Ben White', 'ENG'),
('Forward', 'Jack Grealish', 'ENG'),
('Forward', 'Harry Kane', 'ENG'),
('Forward', 'Raheem Sterling', 'ENG'),
('Forward', 'Marcus Rashford', 'ENG'),
('Forward', 'Bukayo Saka', 'ENG'),
('Forward', 'Callum Wilson', 'ENG'),
('Goalkeeper', 'Jordan Pickford', 'ENG'),
('Goalkeeper', 'Nick Pope', 'ENG'),
('Goalkeeper', 'Aaron Ramsdale', 'ENG'),
('Midfielder', 'Declan Rice', 'ENG'),
('Midfielder', 'Jordan Henderson', 'ENG'),
('Midfielder', 'Kalvin Phillips', 'ENG'),
('Midfielder', 'Mason Mount', 'ENG'),
('Midfielder', 'Phil Foden', 'ENG'),
('Midfielder', 'Jude Bellingham', 'ENG'),
('Midfielder', 'James Maddison', 'ENG'),
('Midfielder', 'Conor Gallagher', 'ENG'),

('Defender', 'Benjamin Pavard', 'FRA'),
('Defender', 'Axel Disasi', 'FRA'),
('Defender', 'Raphaël Varane', 'FRA'),
('Defender', 'Jules Koundé', 'FRA'),
('Defender', 'William Saliba', 'FRA'),
('Defender', 'Dayot Upamecano', 'FRA'),
('Defender', 'Lucas Hernandez', 'FRA'),
('Defender', 'Theo Hernandez', 'FRA'),
('Defender', 'Ibrahima Konaté', 'FRA'),
('Forward', 'Antoine Griezmann', 'FRA'),
('Forward', 'Olivier Giroud', 'FRA'),
('Forward', 'Kylian Mbappé', 'FRA'),
('Forward', 'Ousmane Dembélé', 'FRA'),
('Forward', 'Randal Kolo Muani', 'FRA'),
('Forward', 'Kingsley Coman', 'FRA'),
('Forward', 'Marcus Thuram', 'FRA'),
('Goalkeeper', 'Hugo Lloris', 'FRA'),
('Goalkeeper', 'Steve Mandanda', 'FRA'),
('Goalkeeper', 'Alphonse Areola', 'FRA'),
('Midfielder', 'Matteo Guendouzi', 'FRA'),
('Midfielder', 'Aurélien Tchouaméni', 'FRA'),
('Midfielder', 'Youssouf Fofana', 'FRA'),
('Midfielder', 'Adrien Rabiot', 'FRA'),
('Midfielder', 'Jordan Veretout', 'FRA'),
('Midfielder', 'Eduardo Camavinga', 'FRA'),

('Defender', 'Antonio Rüdiger', 'GER'),
('Defender', 'David Raum', 'GER'),
('Defender', 'Matthias Ginter', 'GER'),
('Defender', 'Thilo Kehrer', 'GER'),
('Defender', 'Niklas Süle', 'GER'),
('Defender', 'Lukas Klostermann', 'GER'),
('Defender', 'Christian Günter', 'GER'),
('Defender', 'Nico Schlotterbeck', 'GER'),
('Defender', 'Armel Bella-Kotchap', 'GER'),
('Forward', 'Kai Havertz', 'GER'),
('Forward', 'Niclas Füllkrug', 'GER'),
('Forward', 'Serge Gnabry', 'GER'),
('Forward', 'Karim Adeyemi', 'GER'),
('Forward', 'Youssoufa Moukoko', 'GER'),
('Goalkeeper', 'Manuel Neuer', 'GER'),
('Goalkeeper', 'Kevin Trapp', 'GER'),
('Goalkeeper', 'Marc-André ter Stegen', 'GER'),
('Midfielder', 'Joshua Kimmich', 'GER'),
('Midfielder', 'Leon Goretzka', 'GER'),
('Midfielder', 'Mario Götze', 'GER'),
('Midfielder', 'Thomas Müller', 'GER'),
('Midfielder', 'Jamal Musiala', 'GER'),
('Midfielder', 'Julian Brandt', 'GER'),
('Midfielder', 'Jonas Hofmann', 'GER'),
('Midfielder', 'Leroy Sané', 'GER'),
('Midfielder', 'İlkay Gündoğan', 'GER'),

('Defender', 'Tariq Lamptey', 'GHA'),
('Defender', 'Denis Odoi', 'GHA'),
('Defender', 'Mohammed Salisu', 'GHA'),
('Defender', 'Gideon Mensah', 'GHA'),
('Defender', 'Joseph Aidoo', 'GHA'),
('Defender', 'Baba Rahman', 'GHA'),
('Defender', 'Daniel Amartey', 'GHA'),
('Defender', 'Alexander Djiku', 'GHA'),
('Defender', 'Alidu Seidu', 'GHA'),
('Forward', 'Jordan Ayew', 'GHA'),
('Forward', 'André Ayew', 'GHA'),
('Forward', 'Iñaki Williams', 'GHA'),
('Forward', 'Antoine Semenyo', 'GHA'),
('Goalkeeper', 'Lawrence Ati-Zigi', 'GHA'),
('Goalkeeper', 'Ibrahim Danlad', 'GHA'),
('Goalkeeper', 'Abdul Manaf Nurudeen', 'GHA'),
('Midfielder', 'Thomas Partey', 'GHA'),
('Midfielder', 'Elisha Owusu', 'GHA'),
('Midfielder', 'Abdul Fatawu Issahaku', 'GHA'),
('Midfielder', 'Daniel-Kofi Kyereh', 'GHA'),
('Midfielder', 'Osman Bukari', 'GHA'),
('Midfielder', 'Daniel Afriyie', 'GHA'),
('Midfielder', 'Mohammed Kudus', 'GHA'),
('Midfielder', 'Salis Abdul Samed', 'GHA'),
('Midfielder', 'Kamaldeen Sulemana', 'GHA'),
('Midfielder', 'Kamal Sowah', 'GHA'),

('Defender', 'Miki Yamane', 'JPN'),
('Defender', 'Shogo Taniguchi', 'JPN'),
('Defender', 'Ko Itakura', 'JPN'),
('Defender', 'Yuto Nagatomo', 'JPN'),
('Defender', 'Takehiro Tomiyasu', 'JPN'),
('Defender', 'Hiroki Sakai', 'JPN'),
('Defender', 'Maya Yoshida', 'JPN'),
('Defender', 'Hiroki Ito', 'JPN'),
('Forward', 'Takuma Asano', 'JPN'),
('Forward', 'Shuto Machino', 'JPN'),
('Forward', 'Ayase Ueda', 'JPN'),
('Forward', 'Daizen Maeda', 'JPN'),
('Goalkeeper', 'Eiji Kawashima', 'JPN'),
('Goalkeeper', 'Shūichi Gonda', 'JPN'),
('Goalkeeper', 'Daniel Schmidt', 'JPN'),
('Midfielder', 'Wataru Endo', 'JPN'),
('Midfielder', 'Gaku Shibasaki', 'JPN'),
('Midfielder', 'Ritsu Dōan', 'JPN'),
('Midfielder', 'Kaoru Mitoma', 'JPN'),
('Midfielder', 'Takumi Minamino', 'JPN'),
('Midfielder', 'Takefusa Kubo', 'JPN'),
('Midfielder', 'Hidemasa Morita', 'JPN'),
('Midfielder', 'Junya Ito', 'JPN'),
('Midfielder', 'Daichi Kamada', 'JPN'),
('Midfielder', 'Ao Tanaka', 'JPN'),
('Midfielder', 'Yuki Soma', 'JPN'),

('Defender', 'Sadegh Moharrami', 'IRN'),
('Defender', 'Ehsan Hajsafi', 'IRN'),
('Defender', 'Shojae Khalilzadeh', 'IRN'),
('Defender', 'Milad Mohammadi', 'IRN'),
('Defender', 'Morteza Pouraliganji', 'IRN'),
('Defender', 'Hossein Kanaanizadegan', 'IRN'),
('Defender', 'Rouzbeh Cheshmi', 'IRN'),
('Defender', 'Majid Hosseini', 'IRN'),
('Defender', 'Ramin Rezaeian', 'IRN'),
('Defender', 'Abolfazl Jalali', 'IRN'),
('Forward', 'Mehdi Taremi', 'IRN'),
('Forward', 'Karim Ansarifard', 'IRN'),
('Forward', 'Sardar Azmoun', 'IRN'),
('Goalkeeper', 'Alireza Beiranvand', 'IRN'),
('Goalkeeper', 'Payam Niazmand', 'IRN'),
('Goalkeeper', 'Amir Abedzadeh', 'IRN'),
('Goalkeeper', 'Hossein Hosseini', 'IRN'),
('Midfielder', 'Saeid Ezatolahi', 'IRN'),
('Midfielder', 'Alireza Jahanbakhsh', 'IRN'),
('Midfielder', 'Vahid Amiri', 'IRN'),
('Midfielder', 'Saman Ghoddos', 'IRN'),
('Midfielder', 'Mehdi Torabi', 'IRN'),
('Midfielder', 'Ali Gholizadeh', 'IRN'),
('Midfielder', 'Ali Karimi', 'IRN'),
('Midfielder', 'Ahmad Nourollahi', 'IRN'),

('Defender', 'Néstor Araujo', 'MEX'),
('Defender', 'César Montes', 'MEX'),
('Defender', 'Edson Álvarez', 'MEX'),
('Defender', 'Johan Vásquez', 'MEX'),
('Defender', 'Gerardo Arteaga', 'MEX'),
('Defender', 'Héctor Moreno', 'MEX'),
('Defender', 'Jorge Sánchez', 'MEX'),
('Defender', 'Jesús Gallardo', 'MEX'),
('Defender', 'Kevin Álvarez', 'MEX'),
('Forward', 'Raúl Jiménez', 'MEX'),
('Forward', 'Alexis Vega', 'MEX'),
('Forward', 'Rogelio Funes Mori', 'MEX'),
('Forward', 'Orbelín Pineda', 'MEX'),
('Forward', 'Henry Martín', 'MEX'),
('Forward', 'Uriel Antuna', 'MEX'),
('Forward', 'Hirving Lozano', 'MEX'),
('Forward', 'Roberto Alvarado', 'MEX'),
('Goalkeeper', 'Alfredo Talavera', 'MEX'),
('Goalkeeper', 'Rodolfo Cota', 'MEX'),
('Goalkeeper', 'Guillermo Ochoa', 'MEX'),
('Midfielder', 'Luis Romo', 'MEX'),
('Midfielder', 'Carlos Rodríguez', 'MEX'),
('Midfielder', 'Érick Gutiérrez', 'MEX'),
('Midfielder', 'Héctor Herrera', 'MEX'),
('Midfielder', 'Andrés Guardado', 'MEX'),
('Midfielder', 'Luis Chávez', 'MEX'),

('Defender', 'Achraf Hakimi', 'MAR'),
('Defender', 'Noussair Mazraoui', 'MAR'),
('Defender', 'Nayef Aguerd', 'MAR'),
('Defender', 'Romain Saïss', 'MAR'),
('Defender', 'Jawad El Yamiq', 'MAR'),
('Defender', 'Achraf Dari', 'MAR'),
('Defender', 'Badr Benoun', 'MAR'),
('Defender', 'Yahia Attiyat Allah', 'MAR'),
('Forward', 'Abderrazak Hamdallah', 'MAR'),
('Forward', 'Abdelhamid Sabiri', 'MAR'),
('Forward', 'Abde Ezzalzouli', 'MAR'),
('Forward', 'Youssef En-Nesyri', 'MAR'),
('Forward', 'Walid Cheddira', 'MAR'),
('Goalkeeper', 'Yassine Bounou', 'MAR'),
('Goalkeeper', 'Munir Mohamedi', 'MAR'),
('Goalkeeper', 'Ahmed Reda Tagnaouti', 'MAR'),
('Midfielder', 'Sofyan Amrabat', 'MAR'),
('Midfielder', 'Hakim Ziyech', 'MAR'),
('Midfielder', 'Azzedine Ounahi', 'MAR'),
('Midfielder', 'Anass Zaroury', 'MAR'),
('Midfielder', 'Ilias Chair', 'MAR'),
('Midfielder', 'Zakaria Aboukhlal', 'MAR'),
('Midfielder', 'Selim Amallah', 'MAR'),
('Midfielder', 'Sofiane Boufal', 'MAR'),
('Midfielder', 'Bilal El Khannous', 'MAR'),
('Midfielder', 'Yahya Jabrane', 'MAR'),

('Defender', 'Jurriën Timber', 'NED'),
('Defender', 'Matthijs de Ligt', 'NED'),
('Defender', 'Virgil van Dijk', 'NED'),
('Defender', 'Nathan Aké', 'NED'),
('Defender', 'Stefan de Vrij', 'NED'),
('Defender', 'Tyrell Malacia', 'NED'),
('Defender', 'Daley Blind', 'NED'),
('Defender', 'Denzel Dumfries', 'NED'),
('Defender', 'Jeremie Frimpong', 'NED'),
('Forward', 'Steven Bergwijn', 'NED'),
('Forward', 'Cody Gakpo', 'NED'),
('Forward', 'Luuk de Jong', 'NED'),
('Forward', 'Memphis Depay', 'NED'),
('Forward', 'Noa Lang', 'NED'),
('Forward', 'Vincent Janssen', 'NED'),
('Forward', 'Wout Weghorst', 'NED'),
('Goalkeeper', 'Remko Pasveer', 'NED'),
('Goalkeeper', 'Justin Bijlow', 'NED'),
('Goalkeeper', 'Andries Noppert', 'NED'),
('Midfielder', 'Steven Berghuis', 'NED'),
('Midfielder', 'Davy Klaassen', 'NED'),
('Midfielder', 'Marten de Roon', 'NED'),
('Midfielder', 'Teun Koopmeiners', 'NED'),
('Midfielder', 'Frenkie de Jong', 'NED'),
('Midfielder', 'Kenneth Taylor', 'NED'),
('Midfielder', 'Xavi Simons', 'NED'),

('Defender', 'Matty Cash', 'POL'),
('Defender', 'Artur Jędrzejczyk', 'POL'),
('Defender', 'Mateusz Wieteska', 'POL'),
('Defender', 'Jan Bednarek', 'POL'),
('Defender', 'Jakub Kiwior', 'POL'),
('Defender', 'Kamil Glik', 'POL'),
('Defender', 'Bartosz Bereszyński', 'POL'),
('Defender', 'Robert Gumny', 'POL'),
('Forward', 'Arkadiusz Milik', 'POL'),
('Forward', 'Robert Lewandowski', 'POL'),
('Forward', 'Karol Świderski', 'POL'),
('Forward', 'Krzysztof Piątek', 'POL'),
('Goalkeeper', 'Wojciech Szczęsny', 'POL'),
('Goalkeeper', 'Łukasz Skorupski', 'POL'),
('Goalkeeper', 'Kamil Grabara', 'POL'),
('Midfielder', 'Krystian Bielik', 'POL'),
('Midfielder', 'Damian Szymański', 'POL'),
('Midfielder', 'Grzegorz Krychowiak', 'POL'),
('Midfielder', 'Kamil Grosicki', 'POL'),
('Midfielder', 'Jakub Kamiński', 'POL'),
('Midfielder', 'Szymon Żurkowski', 'POL'),
('Midfielder', 'Sebastian Szymański', 'POL'),
('Midfielder', 'Piotr Zieliński', 'POL'),
('Midfielder', 'Nicola Zalewski', 'POL'),
('Midfielder', 'Przemysław Frankowski', 'POL'),
('Midfielder', 'Michał Skóraś', 'POL'),

('Defender', 'Diogo Dalot', 'POR'),
('Defender', 'Pepe', 'POR'),
('Defender', 'Rúben Dias', 'POR'),
('Defender', 'Raphaël Guerreiro', 'POR'),
('Defender', 'Danilo Pereira', 'POR'),
('Defender', 'Nuno Mendes', 'POR'),
('Defender', 'João Cancelo', 'POR'),
('Defender', 'António Silva', 'POR'),
('Forward', 'Cristiano Ronaldo', 'POR'),
('Forward', 'André Silva', 'POR'),
('Forward', 'Bernardo Silva', 'POR'),
('Forward', 'João Félix', 'POR'),
('Forward', 'Rafael Leão', 'POR'),
('Forward', 'Ricardo Horta', 'POR'),
('Forward', 'Gonçalo Ramos', 'POR'),
('Goalkeeper', 'Rui Patrício', 'POR'),
('Goalkeeper', 'José Sá', 'POR'),
('Goalkeeper', 'Diogo Costa', 'POR'),
('Midfielder', 'João Palhinha', 'POR'),
('Midfielder', 'Bruno Fernandes', 'POR'),
('Midfielder', 'William Carvalho', 'POR'),
('Midfielder', 'Vitinha', 'POR'),
('Midfielder', 'João Mário', 'POR'),
('Midfielder', 'Rúben Neves', 'POR'),
('Midfielder', 'Matheus Nunes', 'POR'),
('Midfielder', 'Otávio', 'POR'),

('Defender', 'Ró-Ró', 'QAT'),
('Defender', 'Mohammed Waad', 'QAT'),
('Defender', 'Tarek Salman', 'QAT'),
('Defender', 'Musab Kheder', 'QAT'),
('Defender', 'Homam Ahmed', 'QAT'),
('Defender', 'Bassam Al-Rawi', 'QAT'),
('Defender', 'Boualem Khoukhi', 'QAT'),
('Defender', 'Ismaeel Mohammad', 'QAT'),
('Forward', 'Ahmed Alaaeldin', 'QAT'),
('Forward', 'Mohammed Muntari', 'QAT'),
('Forward', 'Akram Afif', 'QAT'),
('Forward', 'Khalid Muneer', 'QAT'),
('Forward', 'Almoez Ali', 'QAT'),
('Goalkeeper', 'Saad Al-Sheeb', 'QAT'),
('Goalkeeper', 'Yousef Hassan', 'QAT'),
('Goalkeeper', 'Meshaal Barsham', 'QAT'),
('Midfielder', 'Abdelkarim Hassan', 'QAT'),
('Midfielder', 'Abdulaziz Hatem', 'QAT'),
('Midfielder', 'Ali Assadalla', 'QAT'),
('Midfielder', 'Hassan Al-Haydos', 'QAT'),
('Midfielder', 'Karim Boudiaf', 'QAT'),
('Midfielder', 'Salem Al-Hajri', 'QAT'),
('Midfielder', 'Assim Madibo', 'QAT'),
('Midfielder', 'Naif Al-Hadhrami', 'QAT'),
('Midfielder', 'Jassem Gaber', 'QAT'),
('Midfielder', 'Mostafa Meshaal', 'QAT'),

('Defender', 'Sultan Al-Ghannam', 'KSA'),
('Defender', 'Abdullah Madu', 'KSA'),
('Defender', 'Abdulelah Al-Amri', 'KSA'),
('Defender', 'Ali Al-Bulaihi', 'KSA'),
('Defender', 'Mohammed Al-Breik', 'KSA'),
('Defender', 'Saud Abdulhamid', 'KSA'),
('Defender', 'Yasser Al-Shahrani', 'KSA'),
('Defender', 'Hassan Al-Tambakti', 'KSA'),
('Forward', 'Firas Al-Buraikan', 'KSA'),
('Forward', 'Salem Al-Dawsari', 'KSA'),
('Forward', 'Saleh Al-Shehri', 'KSA'),
('Forward', 'Hattan Bahebri', 'KSA'),
('Forward', 'Abdulrahman Al-Aboud', 'KSA'),
('Forward', 'Haitham Asiri', 'KSA'),
('Goalkeeper', 'Mohammed Al-Rubaie', 'KSA'),
('Goalkeeper', 'Mohammed Al-Owais', 'KSA'),
('Goalkeeper', 'Nawaf Al-Aqidi', 'KSA'),
('Midfielder', 'Salman Al-Faraj', 'KSA'),
('Midfielder', 'Abdulellah Al-Malki', 'KSA'),
('Midfielder', 'Abdullah Otayf', 'KSA'),
('Midfielder', 'Ali Al-Hassan', 'KSA'),
('Midfielder', 'Sami Al-Najei', 'KSA'),
('Midfielder', 'Nawaf Al-Abed', 'KSA'),
('Midfielder', 'Mohamed Kanno', 'KSA'),
('Midfielder', 'Nasser Al-Dawsari', 'KSA'),
('Midfielder', 'Riyadh Sharahili', 'KSA'),

('Defender', 'Formose Mendy', 'SEN'),
('Defender', 'Kalidou Koulibaly', 'SEN'),
('Defender', 'Pape Abou Cissé', 'SEN'),
('Defender', 'Cheikhou Kouyaté', 'SEN'),
('Defender', 'Moussa N Diaye', 'SEN'),
('Defender', 'Fodé Ballo-Touré', 'SEN'),
('Defender', 'Ismail Jakobs', 'SEN'),
('Defender', 'Youssouf Sabaly', 'SEN'),
('Defender', 'Abdou Diallo', 'SEN'),
('Defender', 'Moustapha Name', 'SEN'),
('Forward', 'Nicolas Jackson', 'SEN'),
('Forward', 'Boulaye Dia', 'SEN'),
('Forward', 'Iliman Ndiaye', 'SEN'),
('Forward', 'Ismaïla Sarr', 'SEN'),
('Forward', 'Famara Diédhiou', 'SEN'),
('Forward', 'Bamba Dieng', 'SEN'),
('Goalkeeper', 'Seny Dieng', 'SEN'),
('Goalkeeper', 'Édouard Mendy', 'SEN'),
('Goalkeeper', 'Alfred Gomis', 'SEN'),
('Midfielder', 'Idrissa Gueye', 'SEN'),
('Midfielder', 'Nampalys Mendy', 'SEN'),
('Midfielder', 'Pathé Ciss', 'SEN'),
('Midfielder', 'Krépin Diatta', 'SEN'),
('Midfielder', 'Pape Matar Sarr', 'SEN'),
('Midfielder', 'Mamadou Loum', 'SEN'),
('Midfielder', 'Pape Gueye', 'SEN'),

('Defender', 'Strahinja Pavlović', 'SRB'),
('Defender', 'Strahinja Eraković', 'SRB'),
('Defender', 'Nikola Milenković', 'SRB'),
('Defender', 'Miloš Veljković', 'SRB'),
('Defender', 'Stefan Mitrović', 'SRB'),
('Defender', 'Srđan Babić', 'SRB'),
('Defender', 'Filip Mladenović', 'SRB'),
('Forward', 'Nemanja Radonjić', 'SRB'),
('Forward', 'Aleksandar Mitrović', 'SRB'),
('Forward', 'Dušan Tadić', 'SRB'),
('Forward', 'Luka Jović', 'SRB'),
('Forward', 'Dušan Vlahović', 'SRB'),
('Forward', 'Filip Đuričić', 'SRB'),
('Goalkeeper', 'Marko Dmitrović', 'SRB'),
('Goalkeeper', 'Predrag Rajković', 'SRB'),
('Goalkeeper', 'Vanja Milinković-Savić', 'SRB'),
('Midfielder', 'Nemanja Maksimović', 'SRB'),
('Midfielder', 'Nemanja Gudelj', 'SRB'),
('Midfielder', 'Andrija Živković', 'SRB'),
('Midfielder', 'Saša Lukić', 'SRB'),
('Midfielder', 'Filip Kostić', 'SRB'),
('Midfielder', 'Uroš Račić', 'SRB'),
('Midfielder', 'Sergej Milinković-Savić', 'SRB'),
('Midfielder', 'Darko Lazović', 'SRB'),
('Midfielder', 'Ivan Ilić', 'SRB'),
('Midfielder', 'Marko Grujić', 'SRB'),

('Defender', 'Yoon Jong-gyu', 'KOR'),
('Defender', 'Kim Jin-su', 'KOR'),
('Defender', 'Kim Min-jae', 'KOR'),
('Defender', 'Hong Chul', 'KOR'),
('Defender', 'Kim Moon-hwan', 'KOR'),
('Defender', 'Kim Young-gwon', 'KOR'),
('Defender', 'Kwon Kyung-won', 'KOR'),
('Defender', 'Kim Tae-hwan', 'KOR'),
('Defender', 'Cho Yu-min', 'KOR'),
('Forward', 'Cho Gue-sung', 'KOR'),
('Forward', 'Hwang Ui-jo', 'KOR'),
('Goalkeeper', 'Kim Seung-gyu', 'KOR'),
('Goalkeeper', 'Song Bum-keun', 'KOR'),
('Goalkeeper', 'Jo Hyeon-woo', 'KOR'),
('Midfielder', 'Jung Woo-young', 'KOR'),
('Midfielder', 'Hwang In-beom', 'KOR'),
('Midfielder', 'Son Heung-min', 'KOR'),
('Midfielder', 'Paik Seung-ho', 'KOR'),
('Midfielder', 'Lee Jae-sung', 'KOR'),
('Midfielder', 'Hwang Hee-chan', 'KOR'),
('Midfielder', 'Son Jun-ho', 'KOR'),
('Midfielder', 'Na Sang-ho', 'KOR'),
('Midfielder', 'Lee Kang-in', 'KOR'),
('Midfielder', 'Kwon Chang-hoon', 'KOR'),
('Midfielder', 'Jeong Woo-yeong', 'KOR'),
('Midfielder', 'Song Min-kyu', 'KOR'),

('Defender', 'César Azpilicueta', 'ESP'),
('Defender', 'Eric García', 'ESP'),
('Defender', 'Pau Torres', 'ESP'),
('Defender', 'Alejandro Balde', 'ESP'),
('Defender', 'Hugo Guillamón', 'ESP'),
('Defender', 'Jordi Alba', 'ESP'),
('Defender', 'Dani Carvajal', 'ESP'),
('Defender', 'Aymeric Laporte', 'ESP'),
('Forward', 'Álvaro Morata', 'ESP'),
('Forward', 'Marco Asensio', 'ESP'),
('Forward', 'Ferran Torres', 'ESP'),
('Forward', 'Nico Williams', 'ESP'),
('Forward', 'Yeremy Pino', 'ESP'),
('Forward', 'Dani Olmo', 'ESP'),
('Forward', 'Pablo Sarabia', 'ESP'),
('Forward', 'Ansu Fati', 'ESP'),
('Goalkeeper', 'Robert Sánchez', 'ESP'),
('Goalkeeper', 'David Raya', 'ESP'),
('Goalkeeper', 'Unai Simón', 'ESP'),
('Midfielder', 'Sergio Busquets', 'ESP'),
('Midfielder', 'Marcos Llorente', 'ESP'),
('Midfielder', 'Koke', 'ESP'),
('Midfielder', 'Gavi', 'ESP'),
('Midfielder', 'Rodri', 'ESP'),
('Midfielder', 'Carlos Soler', 'ESP'),
('Midfielder', 'Pedri', 'ESP'),

('Defender', 'Edimilson Fernandes', 'SUI'),
('Defender', 'Silvan Widmer', 'SUI'),
('Defender', 'Nico Elvedi', 'SUI'),
('Defender', 'Manuel Akanji', 'SUI'),
('Defender', 'Renato Steffen', 'SUI'),
('Defender', 'Ricardo Rodriguez', 'SUI'),
('Defender', 'Eray Cömert', 'SUI'),
('Defender', 'Fabian Schär', 'SUI'),
('Forward', 'Breel Embolo', 'SUI'),
('Forward', 'Haris Seferovic', 'SUI'),
('Forward', 'Ruben Vargas', 'SUI'),
('Forward', 'Noah Okafor', 'SUI'),
('Goalkeeper', 'Yann Sommer', 'SUI'),
('Goalkeeper', 'Jonas Omlin', 'SUI'),
('Goalkeeper', 'Gregor Kobel', 'SUI'),
('Goalkeeper', 'Philipp Köhn', 'SUI'),
('Midfielder', 'Denis Zakaria', 'SUI'),
('Midfielder', 'Remo Freuler', 'SUI'),
('Midfielder', 'Granit Xhaka', 'SUI'),
('Midfielder', 'Michel Aebischer', 'SUI'),
('Midfielder', 'Djibril Sow', 'SUI'),
('Midfielder', 'Christian Fassnacht', 'SUI'),
('Midfielder', 'Fabian Frei', 'SUI'),
('Midfielder', 'Xherdan Shaqiri', 'SUI'),
('Midfielder', 'Fabian Rieder', 'SUI'),
('Midfielder', 'Ardon Jashari', 'SUI'),

('Defender', 'Bilel Ifa', 'TUN'),
('Defender', 'Montassar Talbi', 'TUN'),
('Defender', 'Yassine Meriah', 'TUN'),
('Defender', 'Dylan Bronn', 'TUN'),
('Defender', 'Ali Maâloul', 'TUN'),
('Defender', 'Mohamed Dräger', 'TUN'),
('Defender', 'Wajdi Kechrida', 'TUN'),
('Defender', 'Ali Abdi', 'TUN'),
('Forward', 'Youssef Msakni', 'TUN'),
('Forward', 'Issam Jebali', 'TUN'),
('Forward', 'Wahbi Khazri', 'TUN'),
('Forward', 'Taha Yassine Khenissi', 'TUN'),
('Forward', 'Seifeddine Jaziri', 'TUN'),
('Forward', 'Naïm Sliti', 'TUN'),
('Forward', 'Anis Ben Slimane', 'TUN'),
('Goalkeeper', 'Aymen Mathlouthi', 'TUN'),
('Goalkeeper', 'Aymen Dahmen', 'TUN'),
('Goalkeeper', 'Bechir Ben Saïd', 'TUN'),
('Goalkeeper', 'Mouez Hassen', 'TUN'),
('Midfielder', 'Nader Ghandri', 'TUN'),
('Midfielder', 'Hannibal Mejbri', 'TUN'),
('Midfielder', 'Ferjani Sassi', 'TUN'),
('Midfielder', 'Aïssa Laïdouni', 'TUN'),
('Midfielder', 'Mohamed Ali Ben Romdhane', 'TUN'),
('Midfielder', 'Ellyes Skhiri', 'TUN'),
('Midfielder', 'Ghailene Chaalali', 'TUN'),

('Defender', 'Sergiño Dest', 'USA'),
('Defender', 'Walker Zimmerman', 'USA'),
('Defender', 'Antonee Robinson', 'USA'),
('Defender', 'Tim Ream', 'USA'),
('Defender', 'Aaron Long', 'USA'),
('Defender', 'Shaq Moore', 'USA'),
('Defender', 'Cameron Carter-Vickers', 'USA'),
('Defender', 'DeAndre Yedlin', 'USA'),
('Defender', 'Joe Scally', 'USA'),
('Forward', 'Giovanni Reyna', 'USA'),
('Forward', 'Jesús Ferreira', 'USA'),
('Forward', 'Christian Pulisic', 'USA'),
('Forward', 'Brenden Aaronson', 'USA'),
('Forward', 'Jordan Morris', 'USA'),
('Forward', 'Haji Wright', 'USA'),
('Forward', 'Timothy Weah', 'USA'),
('Forward', 'Josh Sargent', 'USA'),
('Goalkeeper', 'Matt Turner', 'USA'),
('Goalkeeper', 'Ethan Horvath', 'USA'),
('Goalkeeper', 'Sean Johnson', 'USA'),
('Midfielder', 'Tyler Adams', 'USA'),
('Midfielder', 'Yunus Musah', 'USA'),
('Midfielder', 'Weston McKennie', 'USA'),
('Midfielder', 'Luca de la Torre', 'USA'),
('Midfielder', 'Cristian Roldan', 'USA'),
('Midfielder', 'Kellyn Acosta', 'USA'),

('Defender', 'José Giménez', 'URU'),
('Defender', 'Diego Godín', 'URU'),
('Defender', 'Ronald Araújo', 'URU'),
('Defender', 'Guillermo Varela', 'URU'),
('Defender', 'Mathías Olivera', 'URU'),
('Defender', 'Matías Viña', 'URU'),
('Defender', 'Sebastián Coates', 'URU'),
('Defender', 'Martín Cáceres', 'URU'),
('Defender', 'José Luis Rodríguez', 'URU'),
('Forward', 'Facundo Pellistri', 'URU'),
('Forward', 'Luis Suárez', 'URU'),
('Forward', 'Darwin Núñez', 'URU'),
('Forward', 'Maxi Gómez', 'URU'),
('Forward', 'Facundo Torres', 'URU'),
('Forward', 'Edinson Cavani', 'URU'),
('Goalkeeper', 'Fernando Muslera', 'URU'),
('Goalkeeper', 'Sebastián Sosa', 'URU'),
('Goalkeeper', 'Sergio Rochet', 'URU'),
('Midfielder', 'Matías Vecino', 'URU'),
('Midfielder', 'Rodrigo Bentancur', 'URU'),
('Midfielder', 'Nicolás de la Cruz', 'URU'),
('Midfielder', 'Giorgian de Arrascaeta', 'URU'),
('Midfielder', 'Lucas Torreira', 'URU'),
('Midfielder', 'Federico Valverde', 'URU'),
('Midfielder', 'Agustín Canobbio', 'URU'),
('Midfielder', 'Manuel Ugarte', 'URU');